---
# Play1
- name: Generate the SSL certificate and private key
  hosts: ansible-controller
  
  vars_files:
  - ssl.yaml

  tasks:
  - name: Generate private key
    ansible.builtin.openssl_privatekey:
      path: "{{ path_to_cert }}{{ cert_name }}.key"
      size: 2048
  - name: Generate CSR
    ansible.builtin.openssl_csr:
      path: "{{ path_to_cert }}{{ cert_name }}.csr"
      privatekey_path: "{{ path_to_cert }}{{ cert_name }}.key"
  - name: Generate SSL certificate
    ansible.builtin.openssl_certificate:
      provider: selfsigned
      path: "{{ path_to_cert }}{{ cert_name }}.crt"
      privatekey_path: "{{ path_to_cert }}{{ cert_name }}.key"
      csr_path: "{{ path_to_cert }}{{ cert_name }}.csr"


# Play 2
- name: Configure webserver with nginx
  hosts: web
  become: true
  
  vars_files:
    - nginx.yaml
  
  handlers:
  - name: Restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
  
  tasks:
  - name: Ensure that nginx is installed
    ansible.builtin.package:
      name: nginx
      state: latest
      update_cache: true

  - name: Create directory for TLS certificates
    ansible.builtin.file:
      path: "{{ tls_dir }}"
      state: directory
      mode: '0750'

  - name: Copy TLS files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: "{{ tls_dir }}"
      mode: '0600'
    loop:
      - "{{ key_file }}"
      - "{{ cert_file }}"
    notify: Restart nginx

  - name: Create nginx config file
    ansible.builtin.template:
      src: nginx.config.j2
      dest: "{{ conf_file }}"
      mode: '0644'
    notify: Restart nginx

  - name: Enable configuration
    ansible.builtin.file:
      src: "{{ conf_file }}"
      dest: /etc/nginx/sites-enabled/default
      state: link

  - name: Create index.html
    ansible.builtin.template:
      src: index.html.j2
      dest: /usr/share/nginx/html/index.html
      mode: '0644'

# Play 3
- name: Configure the hostname of all servers
  hosts: all
  become: true

  tasks:
  - name: Add the hostname to /etc/hosts
    ansible.builtin.lineinfile:
      path: /etc/hosts
      search_string: '127.0.0.1'
      line: "127.0.0.1 {{ inventory_hostname }}"
      owner: root
      group: root
      mode: '0644'
    register: check

  - name: Set the hostname on each server
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"

  - name: Print the output from /etc/hosts
    ansible.builtin.debug:
      var: check

# Play 4
- name: Create a template that collects the required info
  hosts: all
#  become: true

  tasks:
  - name: Collect the data from template and save it to a local file
    ansible.builtin.template:
      src: info.j2
      dest: ~/server_info.txt
