---
- name: Ensure that nginx is installed
  ansible.builtin.package:
    name: nginx
    state: latest

- name: Create directory for TLS certificates
  ansible.builtin.file:
    path: "{{ tls_dir }}"
    state: directory
    mode: '0750'

- name: Copy TLS files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ tls_dir }}"
    mode: '0600'
  loop:
    - "{{ key_file }}"
    - "{{ cert_file }}"
  notify: Restart nginx

- name: Create nginx config file
  ansible.builtin.template:
    src: nginx.config.j2
    dest: "{{ conf_file }}"
    mode: '0644'
  notify: Restart nginx

- name: Enable configuration
  ansible.builtin.file:
    src: "{{ conf_file }}"
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Create index.html
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: '0644'